import { api } from "@/utils/api"
import Head from "next/head"

export default function Home() {
  const { data } = api.hello.useQuery({
    text: "world!",
  })

  return (
    <>
      <Head>
        <title>Filipino de Cuisine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-6 py-4 flex justify-center items-center max-w-7xl mx-auto w-full">
        <p className="text-6xl">{data?.greeting}</p>
      </main>
    </>
  )
}
